### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by varHarrie** [polar-bears/todoron#2]
- [ ] PWA build
- [x] Add favicon
- [x] More animation effects
- [x] Improve README.md
- [x] Improve components (ScrollArea, Dropdown, Group, Card, Checkbox ...)
- [x] Improve task details
- [ ] Calendar feature
- [ ] I18N
